"""
Django settings for scopes project.

Generated by 'django-admin startproject' using Django 2.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os
import tldextract
import socket

#import dbrouters
#from django.db import connections
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '938czejckcgd!3so2u_0sog8wcpn(-(65_vtp+b-*h5asjogku'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'scopes.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'scopes.wsgi.application'

#DATABASE_ROUTERS = ['dbrouters.to.DemoRouter',]
#DATABASE_APPS_MAPPING = {'mydatabase':'mydatabase'}

# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
from django.http import HttpRequest
from core.host import data
hs = "{}".format(data)


hostname = socket.gethostname()
print (hostname)
url = ''
sub = tldextract.extract(url)
sub_domain = sub.subdomain
if sub_domain !=None and sub_domain !="":
    db_name = sub_domain
else:
    db_name = 'demo'
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': db_name,
        'USER':'root',
        'PASSWORD':'Password@123'
    }
    }
#DATABASE_ROUTERS = ['dbrouters.DbRouter',]

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
# from django.conf import settings
#
# settings.configure(DEBUG=True)

# import os
#
# full_path = "jagadish.py"
# # for fname in os.listdir(path_to_store_settings):
# #     full_path = os.path.join(path_to_store_settings, fname)
# f = open(full_path)
# content = f.read()
# exec(content)

#def tenant_from_request(request):

# subdomain_prefix = hostname.split('.')[0]
# return Tenant.objects.filter(subdomain_prefix=subdomain_prefix).first()
